### ISSUE TITLE
[dired-subtree] dired-subtree-insert behaves strange for non-directory in TRAMP buffers.

### ISSUE THREAD

**Issue by takashihattori** [Fuco1/dired-hacks#105]
`dired-subtree-insert` on a non-directory file in TRAMP buffers inserts "total 0" in the next line while `dired-insert-subdir` raises an error.  In addition, we cannot remove the "total 0" line.

dired-subtree Package-Version: 20160920.130
tramp-version 2.2.13.25.2

**Comment by naclander** [comment]
I beleive this is adrress in #104 , and I don't think this is specific to TRAMP. Can you verify whether the patch in #104 works for you?

**Comment by takashihattori** [comment]
Thank you for your reply.  The patch fixes the problem.

Another problem I found (which may not be related to this issue): `dired-subtree-insert` on an already expanded directory duplicates the contents of subdirectory.

**Comment by naclander** [comment]
@takashihattori I think its related to the same bug, although my patch you installed didn't address that issue. I think I haven't noticed this issue before because I always use `dired-subtree-toggle` instead of explicitly calling `dired-subtree-insert`.

I've added another commit in #104  to fix this. Can you try the latest patch?

**Comment by Fuco1** [comment]
@takashihattori @naclander If this works feel free to close! Thank you both very much for solving this!

**Comment by takashihattori** [comment]
@naclander Thank you again.  The patch works great!
