### ISSUE TITLE
[dired-collapse] Misalignment

### ISSUE THREAD

**Issue by dieggsy** [Fuco1/dired-hacks#108]
My `dired-listing-switches` value is `"-lGXhA --group-directories-first"`, if that's relevant. For some reason, dired-collapse-mode causes a misalignment that seems to be due to the file sizes. See attached pictures.

Left using dired-subdir, right just inside the directory:

With dired-collapse:

![2017-09-22_11 29 11](https://user-images.githubusercontent.com/9020453/30752143-54231728-9f89-11e7-8bc2-10f0a827eb68.png)

Without dired-collapse:

![2017-09-22_11 30 02](https://user-images.githubusercontent.com/9020453/30752153-657adbaa-9f89-11e7-878f-521183c380ea.png)

**Comment by Fuco1** [comment]
Yea, the issue is that the `ls` output is loaded first, then `dired-collapse` goes over the lines where it should "drill down" and replaces them, but it only calls `ls` on that one line.  When `ls` generates the output it knows all the sizes and so adjusts the offsets for all the output accordingly.  We don't have that information when we replace a single line.

There is some code which tries to handle this but apparently it doesn't always work.  I think in your case it's the inode counts (and no groups) that mess it up.  This is because we quite stupidly assume what the output is.

What has to be done is to parse one line of the output before the replacements and try to guess the format, then get the offsets and then pad the output accordingly.

**Comment by dieggsy** [comment]
Huh, turning groups back on does seem to fix this. Could the format be guessed by parsing `dired-listing-switches` ?

**Comment by dieggsy** [comment]
Ah, nevermind - turning on groups only fixes it in the own window case, not the subtree case.

**Comment by dieggsy** [comment]
I see the conversation in #89 is related to my question

**Comment by dieggsy** [comment]
@Fuco1 I'm not completely sure how the internals of dired-collapse work but I gave it a quick look and I'm wondering - could we somehow avoid the `(forward-word)` guessing madness by just using something like `dired-move-to-filename`?

**Comment by Fuco1** [comment]
We use `forward-word` there because we need to "process" each column, as they can all misalign when re-inserted.  Ideally dired would know where which column starts but it does not as it just blindly reads in the `ls` output.

I'm also not sure about emulating the `ls` flags and doing some logic based on that, that seems like a road to hell with all the possible combinations.  Some solid regexp solution might work reasonably well, but I haven't had much time to look into it.

What we need is to fill the variables `user-column group-column date-column` (and possibly others as there are other columns) with either a number (column) or nil if it is not present, and then realign the whole buffer.

Other possibility that comes to me is to grab all the "replacements" and then call `ls` itself with all the data in one call... that might actually work amazingly well (i.e. instead of `ls directory` it would do `ls directory directory/sub/replacement.one directory/sub` ....) `dired` should allow generating such a buffer.

**Comment by Fuco1** [comment]
Actually, you would need to call `ls -d ./* sub/* sub/sub/*` to preserve the paths... so I'm not sure dired can handle such an input.

**Comment by dieggsy** [comment]
I suppose my question is more - if it's aligned at the start, why would using `dired-move-to-filename` and replacing just the dir name misalign stuff? We're simply adding text to the end of the line.

I suppose that's obviously easier said than done (I haven't tried any of this), and you've experimented with this more than I have, so I'll try and play around with this a bit and take your word for it for now :)

**Comment by Fuco1** [comment]
We are replacing all the data, including permissions, owners, size, last modification date etc.

**Comment by dieggsy** [comment]
Silly me - of course, since we're showing the _file_ info, which is the whole point of `dired-collapse`. Thanks for you patience :sweat_smile:

**Comment by Fuco1** [comment]
Turns out dired already has a function `dired-align-file` which does exactly what we want.  I've replaced all of my custom logic with that and it solves 99% of the cases.  I will push a fix shortly, just making sure things work.

**Comment by dieggsy** [comment]
Oh sweet, thanks! Works as far as I can tell.
