### ISSUE TITLE
good or bad idea : rely on phpactor for copying/moving PHP files

### ISSUE THREAD

**Issue by kermorgant** [Fuco1/dired-hacks#129]
Hi,

As explained [on this issue](https://github.com/ejmr/php-mode/issues/451), I've recently discovered phpactor which offers interesting features among which are class:copy or class:move.

As I'm a dired user, i would find it convenient if could continue using it while having phpactor handle copy/move actions when it makes sense.

I might try to code that feature, but I'm ignorant about elisp so I'd first like to ask how feasible that sounds and maybe get some pointers about how to proceed.

Thanks

**Comment by Fuco1** [comment]
Haha, quite funny coincidence as I was just thinking of writing something similar yesterday when I was moving some classes around... updating the namespaces is so damn annoying.

This is definitely doable but in plain dired it will get messy as dired is pretty much a big tangle of shit. My best first attempt would be to advice `dired-copy-file` and call a special implementation based on the file type, then fall back to the original if we don't have a special handler.  You would need to make sure that you make the interface exactly the same so that all the other dired functions would keep working.

If you use `dired-ranger` copy and paste mechanism it would be a bit easier as I use regular `copy-directory` and `copy-file` there.  So we can create a special handler again which would decide what kind of copy function to call and fall back to these two.

I don't know how the tool you are proposing works with directories but if it is smart enough to "just copy" non-php files it should be a lot simpler as we wouldn't have to drill down into the contents.

**Comment by Fuco1** [comment]
This would be better handled by some LSP integration these days.
