### ISSUE TITLE
filtering by multiple extensions error

### ISSUE THREAD

**Issue by vapniks** [Fuco1/dired-hacks#36]
When calling ```dired-filter-by-extension``` with a negative prefix argument, and feeding it ```pdf``` and ```docx``` followed by ```C-g```, I get the following error:
```Invalide function: "docx"```

**Comment by Fuco1** [comment]
Yes, I can confirm this is a bug.  The problem is in the renderer, should be fairly simple to fix, the list is just missing a quote somewhere.  Do you want to try it? :)

**Comment by vapniks** [comment]
To fix it myself you mean? Point me in the right direction and I'll try (what is the renderer?)

**Comment by vapniks** [comment]
I'm a bit busy right now. I've put a bounty on it though.

**Comment by Fuco1** [comment]
This was way too trivial for $15 :) You can send general-purpose donations to my paypal though :D

(I thought the problem was something else, but then I remembered I solved it already for some other thing... so it was just a matter of adding one line telling dired-filter how to render the list/value for the filter)

**Comment by vapniks** [comment]
Did you get the payment?

**Comment by Fuco1** [comment]
No.

**Comment by vapniks** [comment]
hmm.. and you claimed the bounty on bountysource.com right?

**Comment by Fuco1** [comment]
No. I don't really feel comfortable taking money for a one line patch that took me 30 seconds, counting `git push` time. Thanks though :)

**Comment by vapniks** [comment]
OK, np. That's fine by me :)
